### ISSUE TITLE
run as daemon?

### ISSUE THREAD

**Issue by mishaxz** [Hindol/commons#5]
Hello, how can I make this run as a daemon so that it doesn't prevent my application from exiting?

**Comment by hindol** [comment]
@mishaxz Can you please elaborate what you are trying to do?

**Comment by mishaxz** [comment]
monitoring a folder for the life of the program - but as it is programmed currently, it will prevent the program from exiting when the program is finished

**Comment by hindol** [comment]
Yeah, that is actually a bug in the code. Thanks for pointing it out. Ideally we should assign `ExecutorService EXECUTOR = Executors.newSingleThreadExecutor();` inside `Service.start()` and cleanup in `Service.stop()`.

I am terribly busy but you can always send a pull request, :)

**Comment by hindol** [comment]
@mishaxz I have pushed the necessary changes. Please see if that works for you.

**Comment by mishaxz** [comment]
thanks but I removed the code a while ago, so I don't know when I will put it back in. but thanks for fixing it
